### ISSUE TITLE
Getting MockClient memory leak log

### ISSUE THREAD

**Issue by mir1198yusuf** [felixmosh/knex-mock-client#22]
After running a bunch of unit-tests through jest, I get this log 3-4 times in the console.

`
(node:62616) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 start listeners added to [MockClient]. Use emitter.setMaxListeners() to increase limit
`

I dont know if this is of any concern or it is just due to large number of parallel running `async` test functions.

Thanks.

**Comment by mir1198yusuf** [comment]
I have  total 13 `trackers.on` in directory of unit-tests.

**Comment by felixmosh** [comment]
By trackers.on do you mean the tracker that the lib comes with or something else?

**Comment by mir1198yusuf** [comment]
This is how I use it. Since we dont have `step` in this lib like `knex-mock`, I try to make it work this way.

```
test('Name ', async () => {
        
        const response = [
                response of 1st query, response of 2nd query
        ];
        const trx = await knexObj.transaction();

        const a = new A();
        let step = 0;

        tracker.on
            .any(({ method, sql, bindings }: RawQuery) => {
                if (step === 0) {
                    expect(method).toEqual('select');
                    expect(sql).toMatchInlineSnapshot(....);
                    expect(bindings).toEqual([...]);
                }
                step++;

                return true;
            })
            .response(() => {
                return response[step - 1];
            });
        await a.b()
});
```

**Comment by mir1198yusuf** [comment]
> By trackers.on do you mean the tracker that the lib comes with or something else?

Tracker of this lib.

**Comment by felixmosh** [comment]
Tracker.on is not using listeners at all

**Comment by felixmosh** [comment]
Your tests are not written as it meant to be used :]
You should no expect inside query matcher (the `on` part).
The lib provides an `history` object for each type of queries (`select` / `insert` ...)

```js
test('Name ', async () => {
  const trx = await knexObj.transaction();

  const a = new A();
  tracker.on.select(({ sql }) => sql.includes('table_name')).responseOnce({ id: 1, name: 'bla' });
  await a.b(trx);
  await trx.commit();

  expect(tracker.history.select[0].sql).toContain('table_name');
});
```

**Comment by mir1198yusuf** [comment]
- I cannot just rely on `sql.includes('table_name'))` as all queries might be on same table. 
- I want to match entire sql which I am doing using `matchInlineSnapshot` to see if new commit has not unintentionally added/removed query select/returning fields or where clauses or anything else. If it was an intentional change, I can update the jest snapshot of the sql.
- I want to test the order of query in code. No one should unintentionally alter the sequence of queries. This I agree that I can it with `tracker.history.any` but since I have send response also to queries sequentially, I have to use `step` for response. (For first query hitting the client, this response should be send. For second, this should be send & so on). Since `step` is being used in response, I have to maintain (increment) it inside query matcher. So added `expect` there only, so it can fail early if a particular query is not as expected. (Should-be second query is unintentionally changed to first query)

**Comment by mir1198yusuf** [comment]
> Tracker.on is not using listeners at all

Okay! The logs in the first comment regarding listeners in MockClient do not hint any serious concerns right ? In this case, we can close the issue.

**Comment by mir1198yusuf** [comment]
I ran `node --trace-warnings node_modules/jest/bin/jest.js` to trace the log, I got this.

```
(node:71047) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 start listeners added to [MockClient]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:595:17)
    at MockClient.addListener (node:events:617:10)
    at makeTxClient (abc-user/node_modules/knex/lib/execution/transaction.js:335:13)
    at abc-user/node_modules/knex/lib/execution/transaction.js:196:43
    at Transaction_PG.acquireConnection (abc-user/node_modules/knex/lib/execution/transaction.js:254:20)
(node:71047) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 query listeners added to [MockClient]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:595:17)
    at MockClient.addListener (node:events:617:10)
    at makeTxClient (abc-user/node_modules/knex/lib/execution/transaction.js:340:13)
    at abc-user/node_modules/knex/lib/execution/transaction.js:196:43
    at Transaction_PG.acquireConnection (abc-user/node_modules/knex/lib/execution/transaction.js:254:20)
(node:71047) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 query-error listeners added to [MockClient]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:595:17)
    at MockClient.addListener (node:events:617:10)
    at makeTxClient (abc-user/node_modules/knex/lib/execution/transaction.js:345:13)
    at abc-user/node_modules/knex/lib/execution/transaction.js:196:43
    at Transaction_PG.acquireConnection (abc-user/node_modules/knex/lib/execution/transaction.js:254:20)
(node:71047) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 query-response listeners added to [MockClient]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:595:17)
    at MockClient.addListener (node:events:617:10)
    at makeTxClient (abc-user/node_modules/knex/lib/execution/transaction.js:350:13)
    at abc-user/node_modules/knex/lib/execution/transaction.js:196:43
    at Transaction_PG.acquireConnection (abc-user/node_modules/knex/lib/execution/transaction.js:254:20)
```

The warnings are created from `knex` lib, not this lib.
