### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by fifithecat** [felixmosh/knex-mock-client#30]
Based on the example here: https://stackoverflow.com/questions/28165063/how-can-i-mock-a-fake-database-for-when-unit-testing-against-knex

```js
//insertRecord.ts
import { knexInstance } from './logDatabaseConfig';

const insertLog = async (quan: Number) => {
  try {
    await knexInstance('LOG').insert({ sync_quantity: quan, sync_at: new Date() });
  } catch (error) {
    throw new Error('Error insert' + error);
  }
};

export default insertLog;
```

```js
//insertRecord.test.ts
import { expect } from '@jest/globals';
import knex, { Knex } from 'knex';
import { Tracker, getTracker, MockClient } from 'knex-mock-client';
import { faker } from '@faker-js/faker';
import insertLog from './insertLog';

jest.mock('./insertLog', () => {
  return {
    db: knex({ client: MockClient }),
  };
});

describe('log insert tests', () => {
  let tracker: Tracker;

  beforeAll(() => {
    tracker = getTracker();
  });

  afterEach(() => {
    tracker.reset();
  });

  it('should add new log record', async () => {
    tracker.on.insert('LOG');

    const syncQuantity = 1;
    await insertLog(1);

    const insertHistory = tracker.history.insert;

    expect(insertHistory).toHaveLength(1);
    expect(insertHistory[0].method).toEqual('insert');
  });
});
```

```js
TypeError: (0 , insertLog_1.default) is not a function and highlighting - await insertLog(1);
```

Is it a bug or my mistake??? Please point me to the right direction

My dependencies "@faker-js/faker": "^7.2.0", "@types/jest": "^28.1.1", "concurrently": "^7.2.1", "jest": "^28.1.1", "knex-mock-client": "^1.8.4", "nodemon": "^2.0.16", "ts-jest": "^28.0.4"

**Comment by felixmosh** [comment]
Hi @fifithecat , it looks like an issue with your env handling default exports.

You can try to change the `default export` to be `named export`.

```js
//insertRecord.ts
import { knexInstance } from './logDatabaseConfig';

// --v export the insertLog
export const insertLog = async (quan: Number) => {
  try {
    await knexInstance('LOG').insert({ sync_quantity: quan, sync_at: new Date() });
  } catch (error) {
    throw new Error('Error insert' + error);
  }
};
```

```js
//insertRecord.test.ts
import { expect } from '@jest/globals';
import knex, { Knex } from 'knex';
import { Tracker, getTracker, MockClient } from 'knex-mock-client';
import { faker } from '@faker-js/faker';
import { insertLog } from './insertLog';
// ----------^ name import it

jest.mock('./insertLog', () => {
  return {
    db: knex({ client: MockClient }),
  };
});

describe('log insert tests', () => {
  let tracker: Tracker;

  beforeAll(() => {
    tracker = getTracker();
  });

  afterEach(() => {
    tracker.reset();
  });

  it('should add new log record', async () => {
    tracker.on.insert('LOG');

    const syncQuantity = 1;
    await insertLog(1);

    const insertHistory = tracker.history.insert;

    expect(insertHistory).toHaveLength(1);
    expect(insertHistory[0].method).toEqual('insert');
  });
});
```

**Comment by fifithecat** [comment]
Hi felix,

Thank you your reply. No matter named export or default export, it is still not working (while another module able to using the 'insertLog' component in both situation)

Johnny

**Comment by felixmosh** [comment]
Can you prepare a small repo that reproduces the issue?

**Comment by fifithecat** [comment]
Hi Felix,

I changed my code a little bit (probably fixed the last one) and found another error, I guess my problem is about how to initialize the Mock db connection, here is my code

```
//insertLog.ts
import { Knex } from 'knex';
const insertLog = async(knexConfig: Knex<any, unknown>, syncQuantity: Number) => {

    try {
        await knexConfig('DATA_SYNC_LOG')
        .insert({sync_quantity: syncQuantity, sync_at: new Date()});
    } catch (error) {
    throw new Error('Error inserting the log ' + error);
    }  

}

export {insertLog};
```

```
//insertLog.test.ts
import { expect } from '@jest/globals';
import knex, { Knex } from 'knex';
import { getTracker, MockClient } from 'knex-mock-client';

import {insertLog} from './insertLog';

import {dummyDbConn} from '../db_config/dummyConf';


describe('log insert tests', () => {
    let tracker: any;
    const mockDataConn = knex(dummyDbConn);
    tracker = getTracker();
  
    afterEach(() => {
      tracker.reset();
    });
  
    it('should add new log record', async () => {
      
      tracker.on.insert('DATA_SYNC_LOG');
      
      await insertLog(mockDataConn, 1);
  
      //expect(data.id).toEqual(insertId);
  
      const insertHistory = tracker.history.insert;
  
      expect(insertHistory).toHaveLength(1);
      expect(insertHistory[0].method).toEqual('insert');
      //expect(insertHistory[0].bindings).toEqual([newUser.name, newUser.email]);
    });
  });
```

```
//dummyConf.ts
import { Knex, knex } from 'knex';
import dotenv from 'dotenv';
import { getTracker, MockClient } from 'knex-mock-client';
dotenv.config();

const dummyDbConn: Knex.Config = {
    client: MockClient,
    connection: {
        host: process.env.APP_DB_HOST,
        port: parseInt(process.env.APP_DB_PORT || '5432', 10),
        user: process.env.APP_DB_USER,
        password: process.env.APP_DB_PASSWORD,
        database: process.env.APP_DB_NAME
    }
};

export {dummyDbConn}; 
```

New error

  ● log insert tests › should add new log record

    Error inserting the log Error: insert into "DATA_SYNC_LOG" ("sync_at", "sync_quantity") values ('2022-06-09 16:31:39.190', 1) - Mock handler not found

       6 |         .insert({sync_quantity: syncQuantity, sync_at: new Date()});
       7 |     } catch (error) {
    >  8 |     throw new Error('Error inserting the log ' + error);
         |           ^
       9 |     }  
      10 |
      11 | }

      at src/db/insertLog.ts:8:11
          at Generator.throw (<anonymous>)
      at rejected (src/db/insertLog.ts:738:32)
      
      
      Any hints? I will try to prepare my code repository for this error today later
      
      Thanks
      Johnny

**Comment by felixmosh** [comment]
This lib doesn't requires you to provide a connection (the lib ignores it), since there is no real connection to a db (the whole point of this lib).

I'm not sure if this is the reason to the error, but you must provide the response for the the request handler, this means that instead of 
```js
      tracker.on.insert('DATA_SYNC_LOG');
```
it should be
```js
      tracker.on.insert('DATA_SYNC_LOG').responseOnce(2);
      // the meaning is when ever an insert query is executed, return 2 as id.
```

Review the README for more options.

**Comment by fifithecat** [comment]
It is working now for both select and insert test case, this framework is good to use, just need more example especially how to connect to the 'MockClient', I would try to upload my code to repository in weekend

thanks
Johnny
